export const listBks = [
  { id: 1, name: 'Deutsche Bank' },
  { id: 2, name: 'Commerzbank' },
  { id: 3, name: 'DZ Bank' },
  { id: 4, name: 'UniCredit Bank' },
  { id: 5, name: 'BNP Paribas' },
  { id: 6, name: 'Société Générale' },
  { id: 7, name: 'Crédit Agricole' },
  { id: 8, name: 'La Banque Postale' },
  { id: 9, name: 'ING Group' },
  { id: 10, name: 'Rabobank' },
  { id: 11, name: 'ABN AMRO' },
  { id: 12, name: 'Banco Santander' },
  { id: 13, name: 'CaixaBank' },
  { id: 14, name: 'Bankia' },
  { id: 15, name: 'Intesa Sanpaolo' },
  { id: 16, name: 'Banca Monte dei Paschi di Siena' },
  { id: 17, name: 'BPER Banca' },
  { id: 18, name: 'Raiffeisen Bank International' },
  { id: 19, name: 'Erste Group Bank' },
  { id: 20, name: 'KBC Bank' },
  { id: 21, name: 'Belfius Bank' },
  { id: 22, name: 'Nordea Bank' },
  { id: 23, name: 'Swedbank' },
  { id: 24, name: 'SEB (Skandinaviska Enskilda Banken)' },
  { id: 25, name: 'Danske Bank' },
  { id: 26, name: 'Handelsbanken' },
  { id: 27, name: 'Caixa Geral de Depósitos' },
  { id: 28, name: 'Novo Banco' },
  { id: 29, name: 'Bank of Ireland' },
  { id: 30, name: 'AIB Group' },
  { id: 31, name: 'Luminor Bank' },
  { id: 32, name: 'N26 Bank' },
  { id: 33, name: 'Revolut Bank' },
  { id: 34, name: 'Crédit Mutuel' },
  { id: 35, name: 'Bankinter' }
];
